apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ugrv
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0033-tenant/tkrw-pr714-0075-0033-app/devfile-sample-ugrv@sha256:95057434dc26b1b98ee0933bb450a2a162765c9719e7d111b6a911853b29b1e0
        name: my-nodejs
        resources: {}
status: {}
